export const countries = [
    { name: "Argentina", code: "AR", prefix: "+54", flag: "/Argentina.webp", currency: "ARS", rateToUSD: 820 },
    { name: "Australia", code: "AU", prefix: "+61", flag: "/Australia.webp", currency: "AUD", rateToUSD: 1.52 },
    { name: "Belarus", code: "BY", prefix: "+375", flag: "/Belarus.jpg", currency: "BYN", rateToUSD: 3.2 },
    { name: "Belgium", code: "BE", prefix: "+32", flag: "/Belgium.png", currency: "EUR", rateToUSD: 0.92 },
    { name: "Canada", code: "CA", prefix: "+1", flag: "/Canada.png", currency: "CAD", rateToUSD: 1.35 },
    { name: "China", code: "CN", prefix: "+86", flag: "/China.png", currency: "CNY", rateToUSD: 7.15 },
    { name: "Colombia", code: "CO", prefix: "+57", flag: "/Colombia.jpg", currency: "COP", rateToUSD: 3900 },
    { name: "Egypt", code: "EG", prefix: "+20", flag: "/Egypt.png", currency: "EGP", rateToUSD: 30.9 },
    { name: "Eritrea", code: "ER", prefix: "+291", flag: "/Eritrea.png", currency: "ERN", rateToUSD: 15 },
    { name: "Ethiopia", code: "ET", prefix: "+251", flag: "/Ethiopia.png", currency: "ETB", rateToUSD: 56 },
    { name: "France", code: "FR", prefix: "+33", flag: "/France.png", currency: "EUR", rateToUSD: 0.92 },
    { name: "Jordan", code: "JO", prefix: "+962", flag: "/Jordan.webp", currency: "JOD", rateToUSD: 0.71 },
    { name: "Kazakhstan", code: "KZ", prefix: "+7", flag: "/Kazakhstan.png", currency: "KZT", rateToUSD: 450 },
    { name: "Mexico", code: "MX", prefix: "+52", flag: "/Mexico.png", currency: "MXN", rateToUSD: 17.1 },
    { name: "Morocco", code: "MA", prefix: "+212", flag: "/Morocco.png", currency: "MAD", rateToUSD: 10.1 },
    { name: "New Zealand", code: "NZ", prefix: "+64", flag: "/Flag_of_New_Zealand.svg.png", currency: "NZD", rateToUSD: 1.63 },
    { name: "Russia", code: "RU", prefix: "+7", flag: "/Russia.png", currency: "RUB", rateToUSD: 89 },
    { name: "Saudi Arabia", code: "SA", prefix: "+966", flag: "/Saudi Arabia.png", currency: "SAR", rateToUSD: 3.75 },
    { name: "Senegal", code: "SN", prefix: "+221", flag: "/Senegal.webp", currency: "XOF", rateToUSD: 605 },
    { name: "Singapore", code: "SG", prefix: "+65", flag: "/Singapore.webp", currency: "SGD", rateToUSD: 1.34 },
    { name: "Spain", code: "ES", prefix: "+34", flag: "/Spain.png", currency: "EUR", rateToUSD: 0.92 },
    { name: "Taiwan", code: "TW", prefix: "+886", flag: "/Taiwan.png", currency: "TWD", rateToUSD: 31.2 },
    { name: "United Arab Emirates", code: "AE", prefix: "+971", flag: "/United Arab Emirates.png", currency: "AED", rateToUSD: 3.67 },
    { name: "United Kingdom", code: "GB", prefix: "+44", flag: "/United Kingdom.webp", currency: "GBP", rateToUSD: 0.79 },
    { name: "United States", code: "US", prefix: "+1", flag: "/Flag_of_the_United_States.png", currency: "USD", rateToUSD: 1 },
];

// Phone validation rules for each country
export const phoneValidationRules: Record<string, {
    length: number | [number, number];
    startsWith?: string[];
    errorMsg: string
}> = {
    "Argentina": { length: 10, errorMsg: "Phone number must be 10 digits" },
    "Australia": { length: 9, startsWith: ["2", "3", "4", "7", "8"], errorMsg: "Phone number must be 9 digits starting with 2, 3, 4, 7, or 8" },
    "Belarus": { length: 9, startsWith: ["2", "3", "4"], errorMsg: "Phone number must be 9 digits starting with 2, 3, or 4" },
    "Belgium": { length: [8, 9], errorMsg: "Phone number must be 8 or 9 digits" },
    "Canada": { length: 10, startsWith: ["2", "3", "4", "5", "6", "7", "8", "9"], errorMsg: "Phone number must be 10 digits starting with 2-9" },
    "China": { length: [10, 11], startsWith: ["1", "2", "3", "4", "5", "6", "7", "8", "9"], errorMsg: "Phone number must be 10-11 digits" },
    "Colombia": { length: 10, startsWith: ["1", "2", "3", "4", "5", "6", "7", "8"], errorMsg: "Phone number must be 10 digits" },
    "Egypt": { length: 10, errorMsg: "Phone number must be 10 digits" },
    "Eritrea": { length: 7, startsWith: ["1", "2", "7", "8"], errorMsg: "Phone number must be 7 digits starting with 1, 2, 7, or 8" },
    "Ethiopia": { length: 9, startsWith: ["7", "9"], errorMsg: "Phone number must be 9 digits starting with 7 or 9" },
    "France": { length: 9, errorMsg: "Phone number must be 9 digits" },
    "Jordan": { length: 9, startsWith: ["2", "3", "5", "6", "7"], errorMsg: "Phone number must be 9 digits starting with 2, 3, 5, 6, or 7" },
    "Kazakhstan": { length: 10, errorMsg: "Phone number must be 10 digits" },
    "Mexico": { length: 10, errorMsg: "Phone number must be 10 digits" },
    "Morocco": { length: 9, startsWith: ["2", "5", "6", "7"], errorMsg: "Phone number must be 9 digits starting with 2, 5, 6, or 7" },
    "New Zealand": { length: [8, 10], startsWith: ["2", "3", "4", "5", "6", "7", "8", "9"], errorMsg: "Phone number must be 8-10 digits" },
    "Russia": { length: 10, errorMsg: "Phone number must be 10 digits" },
    "Saudi Arabia": { length: 9, startsWith: ["1", "5"], errorMsg: "Phone number must be 9 digits starting with 1 or 5" },
    "Senegal": { length: 9, startsWith: ["3", "7"], errorMsg: "Phone number must be 9 digits starting with 3 or 7" },
    "Singapore": { length: 8, startsWith: ["3", "6", "8", "9"], errorMsg: "Phone number must be 8 digits starting with 3, 6, 8, or 9" },
    "Spain": { length: 9, startsWith: ["6", "7", "8", "9"], errorMsg: "Phone number must be 9 digits starting with 6, 7, 8, or 9" },
    "Taiwan": { length: [8, 10], errorMsg: "Phone number must be 8-10 digits" },
    "United Arab Emirates": { length: 9, startsWith: ["2", "3", "4", "5", "6", "7"], errorMsg: "Phone number must be 9 digits starting with 2-7" },
    "United Kingdom": { length: 10, errorMsg: "Phone number must be 10 digits" },
    "United States": { length: 10, startsWith: ["2", "3", "4", "5", "6", "7", "8", "9"], errorMsg: "Phone number must be 10 digits starting with 2-9" },
};
